# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ding < Formula
  desc "Stream-based alerting daemon — single binary, zero infrastructure"
  homepage "https://ding.ing"
  version "0.14.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ding-labs/ding/releases/download/v0.14.0/ding_darwin_amd64.tar.gz"
      sha256 "26a25e33a093372ebf796a18b059967a1a24a1c62aebae2861dc079da5c7fc9e"

      define_method(:install) do
        bin.install "ding"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ding-labs/ding/releases/download/v0.14.0/ding_darwin_arm64.tar.gz"
      sha256 "a3a75c1882d621b53eda5f9250e4dd3cc947d3335f4db3cf29fa446e4fb02e17"

      define_method(:install) do
        bin.install "ding"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ding-labs/ding/releases/download/v0.14.0/ding_linux_amd64.tar.gz"
      sha256 "6c069c36c1147d43da8455637537e28c453c7a424155d00b24713fc6eae79be1"
      define_method(:install) do
        bin.install "ding"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ding-labs/ding/releases/download/v0.14.0/ding_linux_arm64.tar.gz"
      sha256 "dbb8738ec72d16f1c2b52afe856a48ac980191f870a0f243b3a99cb788431a2f"
      define_method(:install) do
        bin.install "ding"
      end
    end
  end

  test do
    system "#{bin}/ding", "version"
  end
end
