# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ding < Formula
  desc "Stream-based alerting daemon — single binary, zero infrastructure"
  homepage "https://ding.ing"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ding-labs/ding/releases/download/v0.7.1/ding_darwin_amd64.tar.gz"
      sha256 "b27c0ee0f14b3e459e4bbb464277dbeddb2268bcae572e7e1352d7520fcde1c0"

      define_method(:install) do
        bin.install "ding"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ding-labs/ding/releases/download/v0.7.1/ding_darwin_arm64.tar.gz"
      sha256 "850fcafdd78fa31cb6baba84eed9e6b9321377e565f10009895926c98404e47b"

      define_method(:install) do
        bin.install "ding"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ding-labs/ding/releases/download/v0.7.1/ding_linux_amd64.tar.gz"
      sha256 "0cd441c410aae74e4d21a953fc15cdb21fef5bbbd1dc1b50de17df5d5853300d"
      define_method(:install) do
        bin.install "ding"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ding-labs/ding/releases/download/v0.7.1/ding_linux_arm64.tar.gz"
      sha256 "3c98c55147be54a0ac1674826cb828d6a304c155094b357b6899b5057758c909"
      define_method(:install) do
        bin.install "ding"
      end
    end
  end

  test do
    system "#{bin}/ding", "--version"
  end
end
